spring:
  batch:
    job:
      names: ExportJdbcCursorJob
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-postgresql.sql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/batch
    username: postgres
    
logging:
  level:
    '[com.example.demo]': debug
